[package]
name = "cargo-dot"
version = "0.1.0"
authors = ["Max New <maxsnew@gmail.com>"]

[dependencies]
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"

[dependencies.cargo]
git = "https://github.com/rust-lang/cargo"

[[bin]]
name = "cargo-dot"
test = false
doc = true
