[package]
name = "cargo-deps"
version = "0.3.1"
authors = [
    "Kevin K. <kbknapp@gmail.com>",
    "Max New <maxsnew@gmail.com>",
    "Marcin S. <marcin.swieczkowski@gmail.com>",
]
exclude = ["*.png"]
description = "Cargo subcommand for building GraphViz DOT files of dependency graphs"
repository = "https://github.com/m-cat/cargo-deps.git"
readme = "README.md"
license = "MIT"
keywords = ["cargo", "subcommand", "deps", "dot", "graphviz"]
categories = ["development-tools", "development-tools::cargo-plugins"]

[[bin]]
name = "cargo-deps"

[dependencies]
toml = "0.4.10"
clap = "2.32.0"
ansi_term = { version = "0.11.0", optional = true }

[features]
default = ["color"]
color = ["ansi_term"]
