[package]
name = "cargo-graph"
version = "0.1.0"
authors = [
    "Kevin K. <kbknapp@gmail.com>",
    "Max New <maxsnew@gmail.com>"
]
exclude = ["*.png"]
description = "Cargo subcommand for building GraphViz DOT files of dependency graphs"
repository = "https://github.com/kbknapp/cargo-graph.git"
readme = "README.md"
license = "MIT"
keywords = ["cargo", "subcommand", "graph", "dot", "graphviz"]

[[bin]]
name = "cargo-graph"
test = false
doc = true

[dependencies]
toml = "~0.1.22"
clap = "~1.4"
clippy = {version = "~0.0", optional = true}

[features]
default = []
unstable = ["lints"]
lints = ["nightly", "clippy"]
nightly = []
debug = []

